In [61]:
import pandas as pd

In [62]:
df = pd.read_csv("nba_games.csv", index_col=0)

In [63]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,39.0,81.0,0.481,6.0,20.0,0.300,14.0,18.0,...,22.8,29.0,178.0,111.0,DAL,95,1,2016,2015-12-09,True
1,240.0,240.0,36.0,100.0,0.360,7.0,31.0,0.226,16.0,19.0,...,50.0,32.6,152.0,111.0,ATL,98,0,2016,2015-12-09,False
2,240.0,240.0,37.0,85.0,0.435,8.0,19.0,0.421,17.0,23.0,...,20.0,30.9,148.0,116.0,SAS,107,1,2018,2017-10-18,False
3,240.0,240.0,41.0,89.0,0.461,8.0,21.0,0.381,17.0,19.0,...,28.6,30.9,138.0,118.0,MIN,99,0,2018,2017-10-18,True
4,240.0,240.0,27.0,86.0,0.314,6.0,26.0,0.231,15.0,20.0,...,16.8,30.9,157.0,90.0,MEM,92,1,2021,2021-04-30,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,240.0,35.0,81.0,0.432,11.0,26.0,0.423,27.0,36.0,...,34.2,33.7,160.0,118.0,OKC,92,0,2019,2018-10-19,True
17768,240.0,240.0,37.0,74.0,0.500,13.0,25.0,0.520,26.0,37.0,...,25.0,30.0,139.0,129.0,ORL,108,1,2017,2016-12-14,True
17769,240.0,240.0,42.0,89.0,0.472,14.0,33.0,0.424,10.0,20.0,...,25.6,29.9,175.0,126.0,LAC,113,0,2017,2016-12-14,False
17770,240.0,240.0,41.0,85.0,0.482,9.0,26.0,0.346,26.0,30.0,...,27.7,27.1,150.0,126.0,MIA,106,1,2020,2020-09-19,True
17771,240.0,240.0,33.0,85.0,0.388,12.0,44.0,0.273,28.0,34.0,...,51.5,36.2,141.0,114.0,BOS,117,0,2020,2020-09-19,False

In [64]:
def add_target(team):
    team["target"] = team["won"].shift(-1)
    return team

df = df.groupby("team", group_keys=False).apply(add_target)

In [65]:
df[df["team"] == "WAS"]

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
40,240.0,240.0,35.0,80.0,0.438,7.0,24.0,0.292,16.0,22.0,...,50.4,131.0,106.0,UTA,114,1,2016,2016-03-11,False,True
48,240.0,240.0,40.0,94.0,0.426,7.0,23.0,0.304,16.0,17.0,...,27.5,163.0,123.0,PHI,94,1,2016,2016-02-26,True,True
123,240.0,240.0,47.0,87.0,0.540,11.0,33.0,0.333,17.0,23.0,...,33.3,184.0,130.0,OKC,118,0,2022,2022-01-11,True,False
174,240.0,240.0,37.0,73.0,0.507,12.0,30.0,0.400,31.0,36.0,...,35.3,169.0,120.0,CHI,126,1,2020,2020-02-23,False,True
221,240.0,240.0,40.0,92.0,0.435,7.0,27.0,0.259,14.0,20.0,...,34.5,209.0,109.0,NYK,100,0,2019,2019-01-17,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17564,240.0,240.0,47.0,90.0,0.522,9.0,19.0,0.474,22.0,28.0,...,44.5,180.0,129.0,UTA,121,1,2021,2021-04-12,True,True
17641,240.0,240.0,46.0,101.0,0.455,10.0,26.0,0.385,10.0,12.0,...,32.8,200.0,119.0,CHI,107,0,2017,2017-03-17,True,False
17678,240.0,240.0,40.0,100.0,0.400,9.0,46.0,0.196,18.0,19.0,...,33.4,182.0,116.0,TOR,125,1,2019,2018-11-23,False,True
17715,240.0,240.0,47.0,86.0,0.547,16.0,30.0,0.533,20.0,23.0,...,30.8,183.0,139.0,ORL,103,0,2018,2017-12-23,True,False
17716,240.0,240.0,43.0,89.0,0.483,9.0,26.0,0.346,16.0,20.0,...,36.0,229.0,116.0,SAC,120,1,2016,2016-03-30,False,NaN

In [66]:
df["target"][pd.isnull(df["target"])] = 2

/var/folders/x7/th2_kj452h1by6mn7_w_sg940000gn/T/ipykernel_4724/1618397414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["target"][pd.isnull(df["target"])] = 2

In [67]:
df["target"] = df["target"].astype(int, errors="ignore")

In [68]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,240.0,39.0,81.0,0.481,6.0,20.0,0.300,14.0,18.0,...,29.0,178.0,111.0,DAL,95,1,2016,2015-12-09,True,1
1,240.0,240.0,36.0,100.0,0.360,7.0,31.0,0.226,16.0,19.0,...,32.6,152.0,111.0,ATL,98,0,2016,2015-12-09,False,0
2,240.0,240.0,37.0,85.0,0.435,8.0,19.0,0.421,17.0,23.0,...,30.9,148.0,116.0,SAS,107,1,2018,2017-10-18,False,1
3,240.0,240.0,41.0,89.0,0.461,8.0,21.0,0.381,17.0,19.0,...,30.9,138.0,118.0,MIN,99,0,2018,2017-10-18,True,0
4,240.0,240.0,27.0,86.0,0.314,6.0,26.0,0.231,15.0,20.0,...,30.9,157.0,90.0,MEM,92,1,2021,2021-04-30,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,240.0,35.0,81.0,0.432,11.0,26.0,0.423,27.0,36.0,...,33.7,160.0,118.0,OKC,92,0,2019,2018-10-19,True,1
17768,240.0,240.0,37.0,74.0,0.500,13.0,25.0,0.520,26.0,37.0,...,30.0,139.0,129.0,ORL,108,1,2017,2016-12-14,True,2
17769,240.0,240.0,42.0,89.0,0.472,14.0,33.0,0.424,10.0,20.0,...,29.9,175.0,126.0,LAC,113,0,2017,2016-12-14,False,2
17770,240.0,240.0,41.0,85.0,0.482,9.0,26.0,0.346,26.0,30.0,...,27.1,150.0,126.0,MIA,106,1,2020,2020-09-19,True,2
17771,240.0,240.0,33.0,85.0,0.388,12.0,44.0,0.273,28.0,34.0,...,36.2,141.0,114.0,BOS,117,0,2020,2020-09-19,False,2

In [69]:
df["won"].value_counts()

won
True     8886
False    8886
Name: count, dtype: int64

In [70]:
df["target"].value_counts()

target
1    8873
0    8869
2      30
Name: count, dtype: int64

In [71]:
nulls = pd.isnull(df)

In [72]:
nulls = nulls.sum()

In [73]:
nulls = nulls[nulls > 0]

In [74]:
nulls

+/-             17772
mp_max          17772
mp_max.1        17772
+/-_opp         17772
mp_max_opp      17772
mp_max_opp.1    17772
dtype: int64

In [75]:
valid_columns = df.columns[~df.columns.isin(nulls.index)]

In [76]:
valid_columns

Index(['mp', 'mp.1', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=145)

In [77]:
df = df[valid_columns].copy()

In [78]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,240.0,39.0,81.0,0.481,6.0,20.0,0.300,14.0,18.0,...,29.0,178.0,111.0,DAL,95,1,2016,2015-12-09,True,1
1,240.0,240.0,36.0,100.0,0.360,7.0,31.0,0.226,16.0,19.0,...,32.6,152.0,111.0,ATL,98,0,2016,2015-12-09,False,0
2,240.0,240.0,37.0,85.0,0.435,8.0,19.0,0.421,17.0,23.0,...,30.9,148.0,116.0,SAS,107,1,2018,2017-10-18,False,1
3,240.0,240.0,41.0,89.0,0.461,8.0,21.0,0.381,17.0,19.0,...,30.9,138.0,118.0,MIN,99,0,2018,2017-10-18,True,0
4,240.0,240.0,27.0,86.0,0.314,6.0,26.0,0.231,15.0,20.0,...,30.9,157.0,90.0,MEM,92,1,2021,2021-04-30,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,240.0,35.0,81.0,0.432,11.0,26.0,0.423,27.0,36.0,...,33.7,160.0,118.0,OKC,92,0,2019,2018-10-19,True,1
17768,240.0,240.0,37.0,74.0,0.500,13.0,25.0,0.520,26.0,37.0,...,30.0,139.0,129.0,ORL,108,1,2017,2016-12-14,True,2
17769,240.0,240.0,42.0,89.0,0.472,14.0,33.0,0.424,10.0,20.0,...,29.9,175.0,126.0,LAC,113,0,2017,2016-12-14,False,2
17770,240.0,240.0,41.0,85.0,0.482,9.0,26.0,0.346,26.0,30.0,...,27.1,150.0,126.0,MIA,106,1,2020,2020-09-19,True,2
17771,240.0,240.0,33.0,85.0,0.388,12.0,44.0,0.273,28.0,34.0,...,36.2,141.0,114.0,BOS,117,0,2020,2020-09-19,False,2

In [79]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)

sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction="forward", cv=split)

In [107]:
removed_columns = ["season", "date", "won", "target", "team", "team_opp"]

In [81]:
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [82]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [83]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.0,0.454545,0.308824,0.507177,0.206897,0.242424,0.356295,0.302326,0.269841,...,0.088575,0.421801,0.400000,DAL,0.298077,1.0,2016,2015-12-09,True,1
1,0.0,0.0,0.386364,0.588235,0.217703,0.241379,0.409091,0.268409,0.348837,0.285714,...,0.134788,0.298578,0.400000,ATL,0.326923,0.0,2016,2015-12-09,False,0
2,0.0,0.0,0.409091,0.367647,0.397129,0.275862,0.227273,0.500000,0.372093,0.349206,...,0.112965,0.279621,0.458824,SAS,0.413462,1.0,2018,2017-10-18,False,1
3,0.0,0.0,0.500000,0.426471,0.459330,0.275862,0.257576,0.452494,0.372093,0.285714,...,0.112965,0.232227,0.482353,MIN,0.336538,0.0,2018,2017-10-18,True,0
4,0.0,0.0,0.181818,0.382353,0.107656,0.206897,0.333333,0.274347,0.325581,0.301587,...,0.112965,0.322275,0.152941,MEM,0.269231,1.0,2021,2021-04-30,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.0,0.363636,0.308824,0.389952,0.379310,0.333333,0.502375,0.604651,0.555556,...,0.148909,0.336493,0.482353,OKC,0.269231,0.0,2019,2018-10-19,True,1
17768,0.0,0.0,0.409091,0.205882,0.552632,0.448276,0.318182,0.617577,0.581395,0.571429,...,0.101412,0.236967,0.611765,ORL,0.423077,1.0,2017,2016-12-14,True,2
17769,0.0,0.0,0.522727,0.426471,0.485646,0.482759,0.439394,0.503563,0.209302,0.301587,...,0.100128,0.407583,0.576471,LAC,0.471154,0.0,2017,2016-12-14,False,2
17770,0.0,0.0,0.500000,0.367647,0.509569,0.310345,0.333333,0.410926,0.581395,0.460317,...,0.064185,0.289100,0.576471,MIA,0.403846,1.0,2020,2020-09-19,True,2
17771,0.0,0.0,0.318182,0.367647,0.284689,0.413793,0.606061,0.324228,0.627907,0.523810,...,0.181001,0.246445,0.435294,BOS,0.509615,0.0,2020,2020-09-19,False,2

In [84]:
sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [85]:
predictors = list(selected_columns[sfs.get_support()])

In [86]:
predictors

['drb',
 'pf',
 'blk%',
 'usg%',
 'fg_max',
 'orb_max',
 'ts%_max',
 'efg%_max',
 '3par_max',
 'trb%_max',
 'ast%_max',
 'blk%_max',
 'drtg_max',
 '3p_opp',
 '3pa_opp',
 '3p%_opp',
 'fta_opp',
 'ftr_opp',
 'ast%_opp',
 'usg%_opp',
 '3pa_max_opp',
 '3p%_max_opp',
 'fta_max_opp',
 'ast_max_opp',
 'tov_max_opp',
 'pts_max_opp',
 'ts%_max_opp',
 'drb%_max_opp',
 'ast%_max_opp',
 'stl%_max_opp']

In [87]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []

    seasons = sorted(data["season"].unique())

    for i in range(start, len(seasons), step):
        season = seasons[i]

        train = data[data["season"] < season]
        test = data[data["season"] == season]

        model.fit(train[predictors], train["target"])

        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)

        combined = pd.concat([test["target"], preds], axis=1)
        combined.columns = ["actual", "prediction"]

        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [88]:
predictions = backtest(df, rr, predictors)

In [89]:
predictions

       actual  prediction
2           1           0
3           0           1
24          0           1
25          1           0
38          0           1
...       ...         ...
17721       1           0
17748       0           1
17749       2           1
17758       2           1
17759       2           0

[12522 rows x 2 columns]

In [90]:
from sklearn.metrics import accuracy_score

predictions = predictions[predictions["actual"] != 2]
accuracy_score(predictions["actual"], predictions["prediction"])

0.5063189889617661

In [91]:
df.groupby("home").apply(lambda x: x[x["won"]==1].shape[0] / x.shape[0])

home
0.0    0.428314
1.0    0.571686
dtype: float64

In [92]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.0,0.454545,0.308824,0.507177,0.206897,0.242424,0.356295,0.302326,0.269841,...,0.088575,0.421801,0.400000,DAL,0.298077,1.0,2016,2015-12-09,True,1
1,0.0,0.0,0.386364,0.588235,0.217703,0.241379,0.409091,0.268409,0.348837,0.285714,...,0.134788,0.298578,0.400000,ATL,0.326923,0.0,2016,2015-12-09,False,0
2,0.0,0.0,0.409091,0.367647,0.397129,0.275862,0.227273,0.500000,0.372093,0.349206,...,0.112965,0.279621,0.458824,SAS,0.413462,1.0,2018,2017-10-18,False,1
3,0.0,0.0,0.500000,0.426471,0.459330,0.275862,0.257576,0.452494,0.372093,0.285714,...,0.112965,0.232227,0.482353,MIN,0.336538,0.0,2018,2017-10-18,True,0
4,0.0,0.0,0.181818,0.382353,0.107656,0.206897,0.333333,0.274347,0.325581,0.301587,...,0.112965,0.322275,0.152941,MEM,0.269231,1.0,2021,2021-04-30,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.0,0.363636,0.308824,0.389952,0.379310,0.333333,0.502375,0.604651,0.555556,...,0.148909,0.336493,0.482353,OKC,0.269231,0.0,2019,2018-10-19,True,1
17768,0.0,0.0,0.409091,0.205882,0.552632,0.448276,0.318182,0.617577,0.581395,0.571429,...,0.101412,0.236967,0.611765,ORL,0.423077,1.0,2017,2016-12-14,True,2
17769,0.0,0.0,0.522727,0.426471,0.485646,0.482759,0.439394,0.503563,0.209302,0.301587,...,0.100128,0.407583,0.576471,LAC,0.471154,0.0,2017,2016-12-14,False,2
17770,0.0,0.0,0.500000,0.367647,0.509569,0.310345,0.333333,0.410926,0.581395,0.460317,...,0.064185,0.289100,0.576471,MIA,0.403846,1.0,2020,2020-09-19,True,2
17771,0.0,0.0,0.318182,0.367647,0.284689,0.413793,0.606061,0.324228,0.627907,0.523810,...,0.181001,0.246445,0.435294,BOS,0.509615,0.0,2020,2020-09-19,False,2

In [93]:
df_rolling = df[list(selected_columns) + ["won", "team", "season"]]

In [94]:
df_rolling

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,team,season
0,0.0,0.0,0.454545,0.308824,0.507177,0.206897,0.242424,0.356295,0.302326,0.269841,...,0.044,0.190776,0.088575,0.421801,0.400000,0.298077,1.0,True,ATL,2016
1,0.0,0.0,0.386364,0.588235,0.217703,0.241379,0.409091,0.268409,0.348837,0.285714,...,0.062,0.475891,0.134788,0.298578,0.400000,0.326923,0.0,False,DAL,2016
2,0.0,0.0,0.409091,0.367647,0.397129,0.275862,0.227273,0.500000,0.372093,0.349206,...,0.076,0.161426,0.112965,0.279621,0.458824,0.413462,1.0,False,MIN,2018
3,0.0,0.0,0.500000,0.426471,0.459330,0.275862,0.257576,0.452494,0.372093,0.285714,...,0.050,0.251572,0.112965,0.232227,0.482353,0.336538,0.0,True,SAS,2018
4,0.0,0.0,0.181818,0.382353,0.107656,0.206897,0.333333,0.274347,0.325581,0.301587,...,0.113,0.127883,0.112965,0.322275,0.152941,0.269231,1.0,False,ORL,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.0,0.363636,0.308824,0.389952,0.379310,0.333333,0.502375,0.604651,0.555556,...,0.063,0.310273,0.148909,0.336493,0.482353,0.269231,0.0,True,LAC,2019
17768,0.0,0.0,0.409091,0.205882,0.552632,0.448276,0.318182,0.617577,0.581395,0.571429,...,0.038,0.213836,0.101412,0.236967,0.611765,0.423077,1.0,True,LAC,2017
17769,0.0,0.0,0.522727,0.426471,0.485646,0.482759,0.439394,0.503563,0.209302,0.301587,...,0.074,0.220126,0.100128,0.407583,0.576471,0.471154,0.0,False,ORL,2017
17770,0.0,0.0,0.500000,0.367647,0.509569,0.310345,0.333333,0.410926,0.581395,0.460317,...,0.064,0.242138,0.064185,0.289100,0.576471,0.403846,1.0,True,BOS,2020
17771,0.0,0.0,0.318182,0.367647,0.284689,0.413793,0.606061,0.324228,0.627907,0.523810,...,0.048,0.491614,0.181001,0.246445,0.435294,0.509615,0.0,False,MIA,2020

In [ ]:
def find_team_averages(team):
    rolling = team.rolling(10).mean()
    return rolling

df_rolling = df_rolling.groupby(["team", "season"], group_keys=False).apply(find_team_averages)

In [ ]:
df_rolling

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,team,season
0,0.0,0.0,0.454545,0.308824,0.507177,0.206897,0.242424,0.356295,0.302326,0.269841,...,0.044,0.190776,0.088575,0.421801,0.400000,0.298077,1.0,True,ATL,2016
1,0.0,0.0,0.386364,0.588235,0.217703,0.241379,0.409091,0.268409,0.348837,0.285714,...,0.062,0.475891,0.134788,0.298578,0.400000,0.326923,0.0,False,DAL,2016
2,0.0,0.0,0.409091,0.367647,0.397129,0.275862,0.227273,0.500000,0.372093,0.349206,...,0.076,0.161426,0.112965,0.279621,0.458824,0.413462,1.0,False,MIN,2018
3,0.0,0.0,0.500000,0.426471,0.459330,0.275862,0.257576,0.452494,0.372093,0.285714,...,0.050,0.251572,0.112965,0.232227,0.482353,0.336538,0.0,True,SAS,2018
4,0.0,0.0,0.181818,0.382353,0.107656,0.206897,0.333333,0.274347,0.325581,0.301587,...,0.113,0.127883,0.112965,0.322275,0.152941,0.269231,1.0,False,ORL,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.0,0.363636,0.308824,0.389952,0.379310,0.333333,0.502375,0.604651,0.555556,...,0.063,0.310273,0.148909,0.336493,0.482353,0.269231,0.0,True,LAC,2019
17768,0.0,0.0,0.409091,0.205882,0.552632,0.448276,0.318182,0.617577,0.581395,0.571429,...,0.038,0.213836,0.101412,0.236967,0.611765,0.423077,1.0,True,LAC,2017
17769,0.0,0.0,0.522727,0.426471,0.485646,0.482759,0.439394,0.503563,0.209302,0.301587,...,0.074,0.220126,0.100128,0.407583,0.576471,0.471154,0.0,False,ORL,2017
17770,0.0,0.0,0.500000,0.367647,0.509569,0.310345,0.333333,0.410926,0.581395,0.460317,...,0.064,0.242138,0.064185,0.289100,0.576471,0.403846,1.0,True,BOS,2020
17771,0.0,0.0,0.318182,0.367647,0.284689,0.413793,0.606061,0.324228,0.627907,0.523810,...,0.048,0.491614,0.181001,0.246445,0.435294,0.509615,0.0,False,MIA,2020

In [96]:
rolling_cols = [f"{col}_10" for col in df_rolling.columns]
df_rolling.columns = rolling_cols

df = pd.concat([df, df_rolling], axis=1)

In [97]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,team_10,season_10
0,0.0,0.0,0.454545,0.308824,0.507177,0.206897,0.242424,0.356295,0.302326,0.269841,...,0.044,0.190776,0.088575,0.421801,0.400000,0.298077,1.0,True,ATL,2016
1,0.0,0.0,0.386364,0.588235,0.217703,0.241379,0.409091,0.268409,0.348837,0.285714,...,0.062,0.475891,0.134788,0.298578,0.400000,0.326923,0.0,False,DAL,2016
2,0.0,0.0,0.409091,0.367647,0.397129,0.275862,0.227273,0.500000,0.372093,0.349206,...,0.076,0.161426,0.112965,0.279621,0.458824,0.413462,1.0,False,MIN,2018
3,0.0,0.0,0.500000,0.426471,0.459330,0.275862,0.257576,0.452494,0.372093,0.285714,...,0.050,0.251572,0.112965,0.232227,0.482353,0.336538,0.0,True,SAS,2018
4,0.0,0.0,0.181818,0.382353,0.107656,0.206897,0.333333,0.274347,0.325581,0.301587,...,0.113,0.127883,0.112965,0.322275,0.152941,0.269231,1.0,False,ORL,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.0,0.363636,0.308824,0.389952,0.379310,0.333333,0.502375,0.604651,0.555556,...,0.063,0.310273,0.148909,0.336493,0.482353,0.269231,0.0,True,LAC,2019
17768,0.0,0.0,0.409091,0.205882,0.552632,0.448276,0.318182,0.617577,0.581395,0.571429,...,0.038,0.213836,0.101412,0.236967,0.611765,0.423077,1.0,True,LAC,2017
17769,0.0,0.0,0.522727,0.426471,0.485646,0.482759,0.439394,0.503563,0.209302,0.301587,...,0.074,0.220126,0.100128,0.407583,0.576471,0.471154,0.0,False,ORL,2017
17770,0.0,0.0,0.500000,0.367647,0.509569,0.310345,0.333333,0.410926,0.581395,0.460317,...,0.064,0.242138,0.064185,0.289100,0.576471,0.403846,1.0,True,BOS,2020
17771,0.0,0.0,0.318182,0.367647,0.284689,0.413793,0.606061,0.324228,0.627907,0.523810,...,0.048,0.491614,0.181001,0.246445,0.435294,0.509615,0.0,False,MIA,2020

In [98]:
df = df.dropna()

In [99]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,team_10,season_10
0,0.0,0.0,0.454545,0.308824,0.507177,0.206897,0.242424,0.356295,0.302326,0.269841,...,0.044,0.190776,0.088575,0.421801,0.400000,0.298077,1.0,True,ATL,2016
1,0.0,0.0,0.386364,0.588235,0.217703,0.241379,0.409091,0.268409,0.348837,0.285714,...,0.062,0.475891,0.134788,0.298578,0.400000,0.326923,0.0,False,DAL,2016
2,0.0,0.0,0.409091,0.367647,0.397129,0.275862,0.227273,0.500000,0.372093,0.349206,...,0.076,0.161426,0.112965,0.279621,0.458824,0.413462,1.0,False,MIN,2018
3,0.0,0.0,0.500000,0.426471,0.459330,0.275862,0.257576,0.452494,0.372093,0.285714,...,0.050,0.251572,0.112965,0.232227,0.482353,0.336538,0.0,True,SAS,2018
4,0.0,0.0,0.181818,0.382353,0.107656,0.206897,0.333333,0.274347,0.325581,0.301587,...,0.113,0.127883,0.112965,0.322275,0.152941,0.269231,1.0,False,ORL,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.0,0.363636,0.308824,0.389952,0.379310,0.333333,0.502375,0.604651,0.555556,...,0.063,0.310273,0.148909,0.336493,0.482353,0.269231,0.0,True,LAC,2019
17768,0.0,0.0,0.409091,0.205882,0.552632,0.448276,0.318182,0.617577,0.581395,0.571429,...,0.038,0.213836,0.101412,0.236967,0.611765,0.423077,1.0,True,LAC,2017
17769,0.0,0.0,0.522727,0.426471,0.485646,0.482759,0.439394,0.503563,0.209302,0.301587,...,0.074,0.220126,0.100128,0.407583,0.576471,0.471154,0.0,False,ORL,2017
17770,0.0,0.0,0.500000,0.367647,0.509569,0.310345,0.333333,0.410926,0.581395,0.460317,...,0.064,0.242138,0.064185,0.289100,0.576471,0.403846,1.0,True,BOS,2020
17771,0.0,0.0,0.318182,0.367647,0.284689,0.413793,0.606061,0.324228,0.627907,0.523810,...,0.048,0.491614,0.181001,0.246445,0.435294,0.509615,0.0,False,MIA,2020

In [100]:
def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col

def add_col(df, col_name):
    return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))

df["home_next"] = add_col(df, "home")
df["team_opp_next"] = add_col(df, "team_opp")
df["date_next"] = add_col(df, "date")

In [101]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,team_10,season_10,home_next,team_opp_next,date_next
0,0.0,0.0,0.454545,0.308824,0.507177,0.206897,0.242424,0.356295,0.302326,0.269841,...,0.421801,0.400000,0.298077,1.0,True,ATL,2016,0.0,BRK,2017-12-02
1,0.0,0.0,0.386364,0.588235,0.217703,0.241379,0.409091,0.268409,0.348837,0.285714,...,0.298578,0.400000,0.326923,0.0,False,DAL,2016,1.0,SAC,2019-03-26
2,0.0,0.0,0.409091,0.367647,0.397129,0.275862,0.227273,0.500000,0.372093,0.349206,...,0.279621,0.458824,0.413462,1.0,False,MIN,2018,1.0,LAC,2017-03-08
3,0.0,0.0,0.500000,0.426471,0.459330,0.275862,0.257576,0.452494,0.372093,0.285714,...,0.232227,0.482353,0.336538,0.0,True,SAS,2018,0.0,DAL,2021-03-10
4,0.0,0.0,0.181818,0.382353,0.107656,0.206897,0.333333,0.274347,0.325581,0.301587,...,0.322275,0.152941,0.269231,1.0,False,ORL,2021,1.0,GSW,2021-02-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.0,0.363636,0.308824,0.389952,0.379310,0.333333,0.502375,0.604651,0.555556,...,0.336493,0.482353,0.269231,0.0,True,LAC,2019,0.0,ORL,2016-12-14
17768,0.0,0.0,0.409091,0.205882,0.552632,0.448276,0.318182,0.617577,0.581395,0.571429,...,0.236967,0.611765,0.423077,1.0,True,LAC,2017,NaN,None,None
17769,0.0,0.0,0.522727,0.426471,0.485646,0.482759,0.439394,0.503563,0.209302,0.301587,...,0.407583,0.576471,0.471154,0.0,False,ORL,2017,NaN,None,None
17770,0.0,0.0,0.500000,0.367647,0.509569,0.310345,0.333333,0.410926,0.581395,0.460317,...,0.289100,0.576471,0.403846,1.0,True,BOS,2020,NaN,None,None
17771,0.0,0.0,0.318182,0.367647,0.284689,0.413793,0.606061,0.324228,0.627907,0.523810,...,0.246445,0.435294,0.509615,0.0,False,MIA,2020,NaN,None,None

In [102]:
df = df.copy()

In [103]:
full = df.merge(df[rolling_cols + ["team_opp_next", "date_next", "team"]], left_on=["team", "date_next"], right_on=["team_opp_next", "date_next"])

In [104]:
full

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,usg%_max_opp_10_y,ortg_max_opp_10_y,drtg_max_opp_10_y,total_opp_10_y,home_opp_10_y,won_10_y,team_10_y,season_10_y,team_opp_next_y,team_y
0,0.00,0.00,0.454545,0.308824,0.507177,0.206897,0.242424,0.356295,0.302326,0.269841,...,1.000000,0.763033,0.694118,0.692308,1.0,False,BRK,2022,ATL,BRK
1,0.00,0.00,0.500000,0.426471,0.459330,0.275862,0.257576,0.452494,0.372093,0.285714,...,0.354300,0.582938,0.423529,0.432692,1.0,False,DAL,2017,SAS,DAL
2,0.00,0.00,0.340909,0.573529,0.177033,0.379310,0.530303,0.334917,0.279070,0.238095,...,0.223363,0.511848,0.647059,0.653846,0.0,True,NOP,2020,MEM,NOP
3,0.00,0.00,0.363636,0.338235,0.366029,0.310345,0.303030,0.445368,0.255814,0.269841,...,0.148909,0.246445,0.529412,0.538462,0.0,True,ORL,2021,LAC,ORL
4,0.00,0.00,0.568182,0.397059,0.566986,0.344828,0.287879,0.516627,0.604651,0.492063,...,0.070603,0.308057,0.388235,0.375000,0.0,False,PHI,2016,SAC,PHI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17725,0.25,0.25,0.522727,0.544118,0.392344,0.275862,0.378788,0.327791,0.465116,0.476190,...,0.225931,0.644550,0.423529,0.442308,0.0,False,NYK,2017,MIL,NYK
17726,0.25,0.25,0.409091,0.485294,0.308612,0.241379,0.272727,0.377672,0.581395,0.507937,...,0.209243,0.578199,0.435294,0.509615,0.0,False,DET,2020,PHO,DET
17727,0.00,0.00,0.454545,0.250000,0.566986,0.310345,0.272727,0.485748,0.558140,0.412698,...,0.132221,0.293839,0.482353,0.355769,0.0,True,LAC,2016,MEM,LAC
17728,0.00,0.00,0.568182,0.294118,0.672249,0.482759,0.469697,0.475059,0.372093,0.269841,...,0.100128,0.274882,0.411765,0.365385,1.0,False,OKC,2018,LAC,OKC
17729,0.00,0.00,0.363636,0.308824,0.389952,0.379310,0.333333,0.502375,0.604651,0.555556,...,0.245186,0.535545,0.270588,0.461538,1.0,False,ORL,2019,LAC,ORL

In [105]:
full[["team_x", "team_opp_next_x", "team_y", "team_opp_next_y", "date_next" ]]

      team_x team_opp_next_x team_y team_opp_next_y   date_next
0        ATL             BRK    BRK             ATL  2017-12-02
1        SAS             DAL    DAL             SAS  2021-03-10
2        MEM             NOP    NOP             MEM  2018-01-20
3        LAC             ORL    ORL             LAC  2016-02-05
4        SAC             PHI    PHI             SAC  2021-02-09
...      ...             ...    ...             ...         ...
17725    MIL             NYK    NYK             MIL  2018-12-25
17726    PHO             DET    DET             PHO  2022-01-16
17727    MEM             LAC    LAC             MEM  2021-02-26
17728    LAC             OKC    OKC             LAC  2018-10-19
17729    LAC             ORL    ORL             LAC  2016-12-14

[17730 rows x 5 columns]

In [108]:
removed_columns = list(full.columns[full.dtypes == "object"]) + removed_columns

In [109]:
removed_columns

['team_x',
 'team_opp',
 'date',
 'team_10_x',
 'team_opp_next_x',
 'date_next',
 'team_10_y',
 'team_opp_next_y',
 'team_y',
 'season',
 'date',
 'won',
 'target',
 'team',
 'team_opp']

In [110]:
selected_columns = full.columns[~full.columns.isin(removed_columns)]

In [111]:
sfs.fit(full[selected_columns], full["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [112]:
predictors = list(selected_columns[sfs.get_support()])

In [113]:
predictors

['pf',
 'trb%',
 'usg%',
 'fg%_max',
 '3pa_max',
 '3p%_max',
 'ft%_max',
 'stl_max',
 'ts%_max',
 '3par_max',
 'stl%_max',
 'blk%_max',
 'usg%_max',
 '3p%_opp',
 'ft_opp',
 'ast_opp',
 'usg%_opp',
 'ft%_max_opp',
 'drb%_max_opp',
 'home_next',
 'ft%_10_y',
 'pf_10_y',
 'fga_max_10_y',
 'orb_max_10_y',
 'ast%_max_10_y',
 'stl%_max_10_y',
 'blk%_max_10_y',
 '3p_opp_10_y',
 'tov%_opp_10_y',
 '3p_max_opp_10_y']

In [114]:
predictions = backtest(full, rr, predictors)

In [115]:
accuracy_score(predictions["actual"], predictions["prediction"])

0.5683528093484873